services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./shared-uploads:/usr/share/nginx/html/uploads:ro
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge